name: CI

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack
              env:
                  WORKING_DIR: ./slack
            - name: Ballerina Test
              # tests will be skipped if the PR is from a forked repository (as the secrets are not available)
              if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
              uses: ballerina-platform/ballerina-action/@nightly
              run: bal test --test-report --code-coverage --coverage-format=xml ./slack
              env:
                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
                  SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
